//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BddGameOfThronesEntities : DbContext
    {
        public BddGameOfThronesEntities()
            : base("name=BddGameOfThronesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Characters> Characters { get; set; }
        public virtual DbSet<CharactersToHouse> CharactersToHouse { get; set; }
        public virtual DbSet<Houses> Houses { get; set; }
        public virtual DbSet<Relationships> Relationships { get; set; }
    }
}
