//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class relationships
    {
        public int first_character_id { get; set; }
        public int second_character_id { get; set; }
        public int relation_type { get; set; }
    
        public virtual characters characters { get; set; }
        public virtual characters characters1 { get; set; }
    }
}
